name: Main

on:
  push:
    branches:
      - master

env:
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and publish image
        run:
          ./pipe_build_up_test.sh
